"""Write a program to generate a Fibonacci series of numbers.
Starting numbers are 0 and 1,  new number in the series is generated by adding previous two numbers in the series.
Example : 0, 1, 1, 2, 3, 5, 8,13,21,.....
   a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
   b) Generate the series until the element in the series is less than Max number."""

# a) Number of elements printed in the series should be N numbers, Where N is any +ve integer.
N = input("Enter number of elements you want to print:")
a = 0
b = 1
c = 0
print a
print b
for x in range(0, N-2):
    c = a + b
    a = b
    b = c
    print c

# b) Generate the series until the element in the series is less than Max number.
N = input("Enter number of elements you want to print:")
a = 0
b = 1
c = 0
print a
print b
for x in range(0, N):
    c = a + b
    a = b
    b = c
    if c < N:
        print c
